#!/usr/bin/env node
import ts from "typescript";
import fs from "fs";
import path from "path";
import { extractHashTargets } from "./walker.js";
import { generateHashFile } from "./codegen.js";

function findTsConfig(projectPath?: string): string {
  if (projectPath) {
    const resolved = path.resolve(projectPath);
    if (fs.statSync(resolved).isDirectory()) {
      return path.join(resolved, "tsconfig.json");
    }
    return resolved;
  }
  const found = ts.findConfigFile(process.cwd(), ts.sys.fileExists, "tsconfig.json");
  if (!found) {
    console.error("ts-hash: could not find tsconfig.json");
    process.exit(1);
  }
  return found;
}

function parseArgs(argv: string[]): { project?: string; output?: string; hasherImport: string } {
  let project: string | undefined;
  let output: string | undefined;
  let hasherImport = "ts-hash";

  for (let i = 2; i < argv.length; i++) {
    const arg = argv[i];
    if ((arg === "-p" || arg === "--project") && argv[i + 1]) {
      project = argv[++i];
    } else if ((arg === "-o" || arg === "--output") && argv[i + 1]) {
      output = argv[++i];
    } else if (arg === "--hasher-import" && argv[i + 1]) {
      hasherImport = argv[++i];
    } else if (arg === "--help" || arg === "-h") {
      console.log(`ts-hash - generate structural hash functions from @hash-tagged types

usage: ts-hash [options]

options:
  -p, --project <path>       path to tsconfig.json (default: auto-detect)
  -o, --output <path>        output file path (default: hash.gen.ts in project root)
  --hasher-import <module>   module to import Hasher from (default: "ts-hash")
  -h, --help                 show this help`);
      process.exit(0);
    }
  }

  return { project, output, hasherImport };
}

function main() {
  const args = parseArgs(process.argv);
  const configPath = findTsConfig(args.project);
  const projectDir = path.dirname(configPath);

  // Parse tsconfig
  const configFile = ts.readConfigFile(configPath, ts.sys.readFile);
  if (configFile.error) {
    console.error(`ts-hash: error reading ${configPath}:`);
    console.error(ts.flattenDiagnosticMessageText(configFile.error.messageText, "\n"));
    process.exit(1);
  }

  const parsed = ts.parseJsonConfigFileContent(configFile.config, ts.sys, projectDir);
  if (parsed.errors.length > 0) {
    for (const err of parsed.errors) {
      console.error(ts.flattenDiagnosticMessageText(err.messageText, "\n"));
    }
    process.exit(1);
  }

  // Filter out the output file itself from the program's root files
  // to avoid chicken-and-egg issues on subsequent runs
  const outputPath = path.resolve(args.output ?? path.join(projectDir, "hash.gen.ts"));
  const rootFiles = parsed.fileNames.filter((f) => path.resolve(f) !== outputPath);

  // Create program
  const program = ts.createProgram(rootFiles, parsed.options);

  // Extract targets
  const targets = extractHashTargets(program);
  if (targets.length === 0) {
    console.log("ts-hash: no @hash-tagged types found");
    // Still write an empty file so imports don't break
    const emptyFile = `// Auto-generated by ts-hash. Do not edit.\n// No @hash-tagged types found.\n`;
    fs.writeFileSync(outputPath, emptyFile);
    return;
  }

  // Generate
  const code = generateHashFile(targets, args.hasherImport);

  // Check if file changed (avoid unnecessary writes that trigger watchers)
  const existing = fs.existsSync(outputPath) ? fs.readFileSync(outputPath, "utf-8") : null;
  if (existing === code) {
    console.log(`ts-hash: hash.gen.ts is up to date (${targets.length} types)`);
    return;
  }

  fs.writeFileSync(outputPath, code);
  console.log(`ts-hash: wrote ${path.relative(process.cwd(), outputPath)} (${targets.length} types)`);

  // Check if tsconfig has the "hash" path alias
  ensurePathAlias(configPath, configFile.config, outputPath, projectDir);
}

function ensurePathAlias(
  configPath: string,
  config: any,
  outputPath: string,
  projectDir: string,
) {
  const compilerOptions = config.compilerOptions ?? {};
  const paths = compilerOptions.paths ?? {};
  const relativePath = "./" + path.relative(projectDir, outputPath).replace(/\\/g, "/");

  if (paths["hash"] && Array.isArray(paths["hash"])) {
    // Already has a "hash" alias — check if it points to the right file
    if (paths["hash"].includes(relativePath)) return;
  }

  // Add the path alias
  if (!config.compilerOptions) config.compilerOptions = {};
  if (!config.compilerOptions.paths) config.compilerOptions.paths = {};
  config.compilerOptions.paths["hash"] = [relativePath];

  // We need baseUrl for paths to work
  if (!config.compilerOptions.baseUrl) {
    config.compilerOptions.baseUrl = ".";
  }

  fs.writeFileSync(configPath, JSON.stringify(config, null, 2) + "\n");
  console.log(`ts-hash: added "hash" path alias to ${path.basename(configPath)}`);
}

main();
