import { HashTarget, TypeNode } from "./walker.js";

/**
 * Generate hash functions for all extracted targets.
 * Returns the full source text of the generated file.
 */
export function generateHashFile(
  targets: HashTarget[],
  hasherImport: string = "ts-hash",
): string {
  const lines: string[] = [];

  lines.push(`// Auto-generated by ts-hash. Do not edit.`);
  lines.push(`import { Hasher } from "${hasherImport}";`);
  lines.push("");

  // First pass: determine which types need composable versions.
  // Any type that appears as a `ref` target (recursive) needs one,
  // plus any type explicitly marked composable.
  const needsComposable = new Set<string>();
  const refNames = new Set<string>();
  for (const target of targets) {
    if (target.composable) needsComposable.add(target.name);
    collectRefs(target.node, needsComposable);
    collectRefs(target.node, refNames);
  }

  // Emit type aliases for ref targets (recursive types)
  const targetsByName = new Map(targets.map((t) => [t.name, t]));
  for (const refName of refNames) {
    const refTarget = targetsByName.get(refName);
    if (refTarget) {
      const typeParamNames = refTarget.typeParams.map((tp) => tp.name);
      const typeParamStr = refTarget.typeParams.length > 0
        ? `<${typeParamNames.join(", ")}>`
        : "";
      const body = emitTypeAnnotation(refTarget.node, typeParamNames);
      lines.push(`type ${refTarget.name}${typeParamStr} = ${body};`);
    }
  }
  if (refNames.size > 0) lines.push("");

  for (const target of targets) {
    // Collect which type params actually appear in hashable positions
    const usedTypeParams = new Set<string>();
    collectTypeParamUsage(target.node, usedTypeParams);

    const typeParamStr = target.typeParams.length > 0
      ? `<${target.typeParams.map((tp) => {
          // Any type param that appears in a hashable position needs the .hash() constraint
          if (usedTypeParams.has(tp.name)) {
            if (tp.constraint) {
              // Existing constraint — intersect with hash requirement
              const existingConstraint = emitTypeAnnotation(tp.constraint, target.typeParams.map((t) => t.name));
              return `${tp.name} extends ${existingConstraint} & { hash(h: Hasher): void }`;
            }
            return `${tp.name} extends { hash(h: Hasher): void }`;
          }
          if (tp.constraint) {
            const existingConstraint = emitTypeAnnotation(tp.constraint, target.typeParams.map((t) => t.name));
            return `${tp.name} extends ${existingConstraint}`;
          }
          return tp.name;
        }).join(", ")}>`
      : "";

    const valueType = emitTypeAnnotation(target.node, target.typeParams.map((tp) => tp.name));
    const composable = needsComposable.has(target.name);

    if (composable) {
      // Emit the internal composable version
      lines.push(`export function _hash${target.name}${typeParamStr}(h: Hasher, value: ${valueType}): void {`);
      emitHashBody(lines, target.node, "value", "  ", target.typeParams.map((tp) => tp.name));
      lines.push(`}`);
      lines.push("");
    }

    // Emit the public version
    lines.push(`export function hash${target.name}${typeParamStr}(value: ${valueType}): string {`);
    lines.push(`  const h = new Hasher();`);
    if (composable) {
      lines.push(`  _hash${target.name}(h, value);`);
    } else {
      emitHashBody(lines, target.node, "value", "  ", target.typeParams.map((tp) => tp.name));
    }
    lines.push(`  return h.finish();`);
    lines.push(`}`);
    lines.push("");
  }

  return lines.join("\n");
}

/**
 * Collect all `ref` names in a TypeNode tree.
 * These are recursive type references that need composable hash functions.
 */
function collectRefs(node: TypeNode, refs: Set<string>): void {
  switch (node.kind) {
    case "ref":
      refs.add(node.name);
      break;
    case "object":
      for (const prop of node.properties) collectRefs(prop.type, refs);
      break;
    case "array":
      collectRefs(node.element, refs);
      break;
    case "tuple":
      for (const el of node.elements) collectRefs(el.type, refs);
      break;
    case "union":
    case "intersection":
      for (const m of node.members) collectRefs(m, refs);
      break;
    case "indexSignature":
      collectRefs(node.valueType, refs);
      break;
    case "map":
      collectRefs(node.keyType, refs);
      collectRefs(node.valueType, refs);
      break;
    case "set":
      collectRefs(node.elementType, refs);
      break;
  }
}

/**
 * Collect all type parameter names that appear in hashable positions.
 * These need the `{ hash(h: Hasher): void }` constraint in the generated signature.
 */
function collectTypeParamUsage(node: TypeNode, used: Set<string>): void {
  switch (node.kind) {
    case "typeParameter":
      used.add(node.name);
      break;
    case "object":
      for (const prop of node.properties) collectTypeParamUsage(prop.type, used);
      break;
    case "array":
      collectTypeParamUsage(node.element, used);
      break;
    case "tuple":
      for (const el of node.elements) collectTypeParamUsage(el.type, used);
      break;
    case "union":
    case "intersection":
      for (const m of node.members) collectTypeParamUsage(m, used);
      break;
    case "indexSignature":
      collectTypeParamUsage(node.valueType, used);
      break;
    case "map":
      collectTypeParamUsage(node.keyType, used);
      collectTypeParamUsage(node.valueType, used);
      break;
    case "set":
      collectTypeParamUsage(node.elementType, used);
      break;
  }
}

/**
 * Emit a TypeScript type annotation string for a TypeNode.
 */
function emitTypeAnnotation(node: TypeNode, typeParamNames: string[]): string {
  switch (node.kind) {
    case "string": return "string";
    case "number": return "number";
    case "boolean": return "boolean";
    case "bigint": return "bigint";
    case "null": return "null";
    case "undefined": return "undefined";
    case "void": return "void";
    case "stringLiteral": return JSON.stringify(node.value);
    case "numberLiteral": return String(node.value);
    case "booleanLiteral": return String(node.value);
    case "typeParameter": return node.name;
    case "ref": return node.name;

    case "array":
      const el = emitTypeAnnotation(node.element, typeParamNames);
      return el.includes("|") || el.includes("&") ? `(${el})[]` : `${el}[]`;

    case "tuple":
      return `[${node.elements.map((e) => {
        const t = emitTypeAnnotation(e.type, typeParamNames);
        return e.optional ? `${t}?` : t;
      }).join(", ")}]`;

    case "union":
      return node.members.map((m) => emitTypeAnnotation(m, typeParamNames)).join(" | ");

    case "intersection":
      return node.members.map((m) => emitTypeAnnotation(m, typeParamNames)).join(" & ");

    case "indexSignature":
      return `{ [key: ${node.keyType}]: ${emitTypeAnnotation(node.valueType, typeParamNames)} }`;

    case "object": {
      const props = node.properties
        .filter((p) => !p.name.startsWith("["))
        .map((p) => {
          const opt = p.optional ? "?" : "";
          return `${p.name}${opt}: ${emitTypeAnnotation(p.type, typeParamNames)}`;
        });
      // Check for index signatures attached as pseudo-properties
      const indexProps = node.properties.filter((p) => p.name.startsWith("["));
      for (const ip of indexProps) {
        if (ip.type.kind === "indexSignature") {
          props.push(`[key: ${ip.type.keyType}]: ${emitTypeAnnotation(ip.type.valueType, typeParamNames)}`);
        }
      }
      return `{ ${props.join("; ")} }`;
    }

    case "enum":
      return node.members.map((m) =>
        typeof m.value === "string" ? JSON.stringify(m.value) : String(m.value)
      ).join(" | ");

    case "date":
      return "Date";

    case "map":
      return `Map<${emitTypeAnnotation(node.keyType, typeParamNames)}, ${emitTypeAnnotation(node.valueType, typeParamNames)}>`;

    case "set":
      return `Set<${emitTypeAnnotation(node.elementType, typeParamNames)}>`;

    default:
      return "unknown";
  }
}

/**
 * Emit hash statements for a TypeNode into the lines array.
 * `accessor` is the expression to access the current value (e.g. "value", "value.name", "el").
 */
function emitHashBody(
  lines: string[],
  node: TypeNode,
  accessor: string,
  indent: string,
  typeParamNames: string[],
  depth: number = 0,
): void {
  switch (node.kind) {
    case "string":
      lines.push(`${indent}h.str(${accessor});`);
      break;

    case "number":
      lines.push(`${indent}h.f64(${accessor});`);
      break;

    case "boolean":
      lines.push(`${indent}h.bool(${accessor});`);
      break;

    case "bigint":
      lines.push(`${indent}h.bigint(${accessor});`);
      break;

    case "null":
      lines.push(`${indent}h.null();`);
      break;

    case "undefined":
      lines.push(`${indent}h.undefined();`);
      break;

    case "void":
      lines.push(`${indent}h.undefined();`);
      break;

    case "stringLiteral":
      lines.push(`${indent}h.str(${accessor});`);
      break;

    case "numberLiteral":
      lines.push(`${indent}h.f64(${accessor});`);
      break;

    case "booleanLiteral":
      lines.push(`${indent}h.bool(${accessor});`);
      break;

    case "typeParameter":
      // Generic T — call .hash() on the value
      lines.push(`${indent}${accessor}.hash(h);`);
      break;

    case "ref":
      // Recursive reference — call the generated hash function
      lines.push(`${indent}_hash${node.name}(h, ${accessor});`);
      break;

    case "array": {
      const elVar = depth === 0 ? "_el" : `_el${depth}`;
      lines.push(`${indent}h.u32(${accessor}.length);`);
      lines.push(`${indent}for (const ${elVar} of ${accessor}) {`);
      emitHashBody(lines, node.element, elVar, indent + "  ", typeParamNames, depth + 1);
      lines.push(`${indent}}`);
      break;
    }

    case "tuple":
      node.elements.forEach((el, i) => {
        const elAccessor = `${accessor}[${i}]`;
        if (el.optional) {
          lines.push(`${indent}if (${elAccessor} !== undefined) {`);
          lines.push(`${indent}  h.u8(1);`);
          emitHashBody(lines, el.type, elAccessor, indent + "  ", typeParamNames, depth);
          lines.push(`${indent}} else {`);
          lines.push(`${indent}  h.u8(0);`);
          lines.push(`${indent}}`);
        } else {
          emitHashBody(lines, el.type, elAccessor, indent, typeParamNames, depth);
        }
      });
      break;

    case "union":
      emitUnionHash(lines, node.members, accessor, indent, typeParamNames, depth);
      break;

    case "intersection":
      // Hash all constituent parts — intersection means all types apply
      for (const member of node.members) {
        emitHashBody(lines, member, accessor, indent, typeParamNames, depth);
      }
      break;

    case "indexSignature":
      emitIndexSignatureHash(lines, node, accessor, indent, typeParamNames, depth);
      break;

    case "object":
      emitObjectHash(lines, node, accessor, indent, typeParamNames, depth);
      break;

    case "enum":
      // Enum values are strings or numbers — hash the runtime value
      lines.push(`${indent}if (typeof ${accessor} === "string") {`);
      lines.push(`${indent}  h.u8(0);`);
      lines.push(`${indent}  h.str(${accessor});`);
      lines.push(`${indent}} else {`);
      lines.push(`${indent}  h.u8(1);`);
      lines.push(`${indent}  h.f64(${accessor});`);
      lines.push(`${indent}}`);
      break;

    case "date":
      lines.push(`${indent}h.u8(0xD0);`); // tag: Date
      lines.push(`${indent}h.f64(${accessor}.getTime());`);
      break;

    case "map": {
      const entryVar = depth === 0 ? "_entry" : `_entry${depth}`;
      lines.push(`${indent}h.u8(0xD1);`); // tag: Map
      if (isPrimitiveNode(node.keyType)) {
        // Primitive keys: simple comparison
        lines.push(`${indent}const ${entryVar}s = [...${accessor}.entries()].sort((a, b) => a[0] < b[0] ? -1 : a[0] > b[0] ? 1 : 0);`);
        lines.push(`${indent}h.u32(${entryVar}s.length);`);
        lines.push(`${indent}for (const ${entryVar} of ${entryVar}s) {`);
        emitHashBody(lines, node.keyType, `${entryVar}[0]`, indent + "  ", typeParamNames, depth + 1);
        emitHashBody(lines, node.valueType, `${entryVar}[1]`, indent + "  ", typeParamNames, depth + 1);
        lines.push(`${indent}}`);
      } else {
        // Complex keys: hash each key once, sort by hash, feed hash + value into hasher
        const pairVar = depth === 0 ? "_pair" : `_pair${depth}`;
        const kVar = depth === 0 ? "_k" : `_k${depth}`;
        lines.push(`${indent}const ${entryVar}s = [...${accessor}.entries()].map(([${kVar}, v]) => {`);
        lines.push(`${indent}  const h = new Hasher();`);
        emitHashBody(lines, node.keyType, kVar, indent + "  ", typeParamNames, depth + 1);
        lines.push(`${indent}  return [h.digest(), v] as const;`);
        lines.push(`${indent}});`);
        lines.push(`${indent}${entryVar}s.sort((a, b) => a[0] < b[0] ? -1 : a[0] > b[0] ? 1 : 0);`);
        lines.push(`${indent}h.u32(${entryVar}s.length);`);
        lines.push(`${indent}for (const ${pairVar} of ${entryVar}s) {`);
        lines.push(`${indent}  h.str(${pairVar}[0]);`);
        emitHashBody(lines, node.valueType, `${pairVar}[1]`, indent + "  ", typeParamNames, depth + 1);
        lines.push(`${indent}}`);
      }
      break;
    }

    case "set": {
      const elVar = depth === 0 ? "_el" : `_el${depth}`;
      lines.push(`${indent}h.u8(0xD2);`); // tag: Set
      if (isPrimitiveNode(node.elementType)) {
        // Primitive elements: simple sort
        lines.push(`${indent}const _sorted${depth || ""} = [...${accessor}.values()].sort();`);
        lines.push(`${indent}h.u32(_sorted${depth || ""}.length);`);
        lines.push(`${indent}for (const ${elVar} of _sorted${depth || ""}) {`);
        emitHashBody(lines, node.elementType, elVar, indent + "  ", typeParamNames, depth + 1);
        lines.push(`${indent}}`);
      } else {
        // Complex elements: hash each once, sort by hash, feed hashes into hasher
        const rawVar = depth === 0 ? "_raw" : `_raw${depth}`;
        lines.push(`${indent}const _hashed${depth || ""} = [...${accessor}.values()].map((${rawVar}) => {`);
        lines.push(`${indent}  const h = new Hasher();`);
        emitHashBody(lines, node.elementType, rawVar, indent + "  ", typeParamNames, depth + 1);
        lines.push(`${indent}  return h.digest();`);
        lines.push(`${indent}});`);
        lines.push(`${indent}_hashed${depth || ""}.sort();`);
        lines.push(`${indent}h.u32(_hashed${depth || ""}.length);`);
        lines.push(`${indent}for (const ${elVar} of _hashed${depth || ""}) {`);
        lines.push(`${indent}  h.str(${elVar});`);
        lines.push(`${indent}}`);
      }
      break;
    }
  }
}

function emitObjectHash(
  lines: string[],
  node: { kind: "object"; properties: { name: string; type: TypeNode; optional: boolean }[] },
  accessor: string,
  indent: string,
  typeParamNames: string[],
  depth: number = 0,
): void {
  for (const prop of node.properties) {
    // Skip pseudo-property index signatures — handled separately
    if (prop.name.startsWith("[")) {
      if (prop.type.kind === "indexSignature") {
        emitIndexSignatureHash(lines, prop.type, accessor, indent, typeParamNames, depth);
      }
      continue;
    }

    const propAccessor = isValidIdentifier(prop.name)
      ? `${accessor}.${prop.name}`
      : `${accessor}[${JSON.stringify(prop.name)}]`;
    if (prop.optional) {
      lines.push(`${indent}if (${propAccessor} !== undefined) {`);
      lines.push(`${indent}  h.u8(1);`);
      emitHashBody(lines, prop.type, propAccessor, indent + "  ", typeParamNames, depth);
      lines.push(`${indent}} else {`);
      lines.push(`${indent}  h.u8(0);`);
      lines.push(`${indent}}`);
    } else {
      emitHashBody(lines, prop.type, propAccessor, indent, typeParamNames, depth);
    }
  }
}

function emitIndexSignatureHash(
  lines: string[],
  node: { kind: "indexSignature"; keyType: "string" | "number"; valueType: TypeNode },
  accessor: string,
  indent: string,
  typeParamNames: string[],
  depth: number = 0,
): void {
  const keysVar = depth === 0 ? "_keys" : `_keys${depth}`;
  const kVar = depth === 0 ? "_k" : `_k${depth}`;
  lines.push(`${indent}const ${keysVar} = Object.keys(${accessor}).sort();`);
  lines.push(`${indent}h.u32(${keysVar}.length);`);
  lines.push(`${indent}for (const ${kVar} of ${keysVar}) {`);
  if (node.keyType === "string") {
    lines.push(`${indent}  h.str(${kVar});`);
  } else {
    lines.push(`${indent}  h.f64(Number(${kVar}));`);
  }
  emitHashBody(lines, node.valueType, `${accessor}[${kVar}]`, indent + "  ", typeParamNames, depth + 1);
  lines.push(`${indent}}`);
}

function emitUnionHash(
  lines: string[],
  members: TypeNode[],
  accessor: string,
  indent: string,
  typeParamNames: string[],
  depth: number = 0,
): void {
  // Check if this is a nullable type (T | null, T | undefined, T | null | undefined)
  const nullMember = members.find((m) => m.kind === "null");
  const undefinedMember = members.find((m) => m.kind === "undefined");
  const nonNullMembers = members.filter((m) => m.kind !== "null" && m.kind !== "undefined");

  if ((nullMember || undefinedMember) && nonNullMembers.length > 0) {
    // Peel off null/undefined, emit a null check, then recurse on the rest
    const condition = nullMember && undefinedMember
      ? `${accessor} != null`
      : nullMember
        ? `${accessor} !== null`
        : `${accessor} !== undefined`;

    lines.push(`${indent}if (${condition}) {`);
    lines.push(`${indent}  h.u8(1);`);
    if (nonNullMembers.length === 1) {
      emitHashBody(lines, nonNullMembers[0], accessor, indent + "  ", typeParamNames, depth);
    } else {
      emitUnionHash(lines, nonNullMembers, accessor, indent + "  ", typeParamNames, depth);
    }
    lines.push(`${indent}} else {`);
    lines.push(`${indent}  h.u8(0);`);
    lines.push(`${indent}}`);
    return;
  }

  // Check for discriminated unions — objects with a shared literal-typed property
  const discriminant = findDiscriminant(members);
  if (discriminant) {
    const { field, branches } = discriminant;
    let first = true;
    for (const [litValue, member] of branches) {
      const cond = typeof litValue === "string"
        ? `${accessor}.${field} === ${JSON.stringify(litValue)}`
        : typeof litValue === "boolean"
          ? `${accessor}.${field} === ${litValue}`
          : `${accessor}.${field} === ${litValue}`;

      if (first) {
        lines.push(`${indent}if (${cond}) {`);
        first = false;
      } else {
        lines.push(`${indent}} else if (${cond}) {`);
      }
      emitHashBody(lines, member, accessor, indent + "  ", typeParamNames, depth);
    }
    lines.push(`${indent}}`);
    return;
  }

  // Split object-like types that typeof can't distinguish.
  // Order: instanceof checks (Date, Map, Set), Array.isArray, then plain objects.
  const instanceofKinds: { kind: string; ctor: string }[] = [
    { kind: "date", ctor: "Date" },
    { kind: "map", ctor: "Map" },
    { kind: "set", ctor: "Set" },
  ];
  const arrayMembers = members.filter((m) => m.kind === "array" || m.kind === "tuple");
  const instanceofMembers = members.filter((m) => instanceofKinds.some((ik) => ik.kind === m.kind));
  const plainMembers = members.filter(
    (m) => !instanceofKinds.some((ik) => ik.kind === m.kind)
      && m.kind !== "array" && m.kind !== "tuple",
  );

  // If we have a mix of instanceof/array/plain types, emit branching.
  // Also fires when we have instanceof + array but no plain members (e.g. Set | string[])
  const needsInstanceofSplit = instanceofMembers.length > 0
    && (arrayMembers.length > 0 || plainMembers.length > 0);
  const needsArraySplit = arrayMembers.length > 0 && plainMembers.length > 0;
  if (needsInstanceofSplit || needsArraySplit) {
    let first = true;

    // instanceof checks first
    for (const member of instanceofMembers) {
      const ctor = instanceofKinds.find((ik) => ik.kind === member.kind)!.ctor;
      if (first) {
        lines.push(`${indent}if (${accessor} instanceof ${ctor}) {`);
        first = false;
      } else {
        lines.push(`${indent}} else if (${accessor} instanceof ${ctor}) {`);
      }
      emitHashBody(lines, member, accessor, indent + "  ", typeParamNames, depth);
    }

    // Array.isArray check
    if (arrayMembers.length > 0) {
      if (first) {
        lines.push(`${indent}if (Array.isArray(${accessor})) {`);
        first = false;
      } else {
        lines.push(`${indent}} else if (Array.isArray(${accessor})) {`);
      }
      if (arrayMembers.length === 1) {
        emitHashBody(lines, arrayMembers[0], accessor, indent + "  ", typeParamNames, depth);
      } else {
        emitUnionHash(lines, arrayMembers, accessor, indent + "  ", typeParamNames, depth);
      }
    }

    // Remaining types in else branch (if any)
    if (plainMembers.length > 0) {
      lines.push(`${indent}} else {`);
      if (plainMembers.length === 1) {
        emitHashBody(lines, plainMembers[0], accessor, indent + "  ", typeParamNames, depth);
      } else {
        emitUnionHash(lines, plainMembers, accessor, indent + "  ", typeParamNames, depth);
      }
    }
    lines.push(`${indent}}`);
    return;
  }

  // Primitive unions — discriminate by typeof
  const typeofBranches = groupByTypeof(members);
  if (typeofBranches) {
    let first = true;
    for (const [typeofStr, branchMembers] of typeofBranches) {
      if (first) {
        lines.push(`${indent}if (typeof ${accessor} === "${typeofStr}") {`);
        first = false;
      } else {
        lines.push(`${indent}} else if (typeof ${accessor} === "${typeofStr}") {`);
      }
      if (branchMembers.length === 1) {
        emitHashBody(lines, branchMembers[0], accessor, indent + "  ", typeParamNames, depth);
      } else {
        // Multiple members with same typeof — emit nested union
        emitUnionHash(lines, branchMembers, accessor, indent + "  ", typeParamNames, depth);
      }
    }
    lines.push(`${indent}}`);
    return;
  }

  // Fallback: hash as JSON string (shouldn't happen for well-structured types)
  lines.push(`${indent}h.str(JSON.stringify(${accessor}));`);
}

/**
 * Try to find a discriminant field in a union of object types.
 * Returns the field name and a map of literal value → member.
 */
function isPrimitiveNode(node: TypeNode): boolean {
  return node.kind === "string" || node.kind === "number"
    || node.kind === "boolean" || node.kind === "bigint"
    || node.kind === "stringLiteral" || node.kind === "numberLiteral"
    || node.kind === "booleanLiteral";
}

const IDENT_RE = /^[a-zA-Z_$][a-zA-Z0-9_$]*$/;
function isValidIdentifier(name: string): boolean {
  return IDENT_RE.test(name);
}

function findDiscriminant(
  members: TypeNode[],
): { field: string; branches: [string | number | boolean, TypeNode][] } | null {
  // All members must be objects
  if (!members.every((m) => m.kind === "object")) return null;

  const objects = members as { kind: "object"; properties: { name: string; type: TypeNode; optional: boolean }[] }[];

  // Find all property names shared by every member
  const allNames = objects[0].properties.map((p) => p.name);
  const sharedNames = allNames.filter((name) =>
    objects.every((obj) => obj.properties.some((p) => p.name === name)),
  );

  // Look for a property where every member has a distinct literal type
  for (const name of sharedNames) {
    const literals: [string | number | boolean, TypeNode][] = [];
    let isDiscriminant = true;
    const seen = new Set<string>();

    for (const obj of objects) {
      const prop = obj.properties.find((p) => p.name === name)!;
      let litValue: string | number | boolean | null = null;

      if (prop.type.kind === "stringLiteral") litValue = prop.type.value;
      else if (prop.type.kind === "numberLiteral") litValue = prop.type.value;
      else if (prop.type.kind === "booleanLiteral") litValue = prop.type.value;

      if (litValue === null) { isDiscriminant = false; break; }

      const key = String(litValue);
      if (seen.has(key)) { isDiscriminant = false; break; }
      seen.add(key);
      literals.push([litValue, obj]);
    }

    if (isDiscriminant && literals.length === objects.length) {
      return { field: name, branches: literals };
    }
  }

  return null;
}

/**
 * Group union members by their typeof result.
 * Returns null if members can't be cleanly distinguished by typeof.
 */
function groupByTypeof(members: TypeNode[]): Map<string, TypeNode[]> | null {
  const groups = new Map<string, TypeNode[]>();

  for (const member of members) {
    const t = typeofKind(member);
    if (!t) return null;

    if (!groups.has(t)) groups.set(t, []);
    groups.get(t)!.push(member);
  }

  // If all members have the same typeof, this doesn't help
  if (groups.size <= 1) return null;

  return groups;
}

function typeofKind(node: TypeNode): string | null {
  switch (node.kind) {
    case "string":
    case "stringLiteral":
      return "string";
    case "number":
    case "numberLiteral":
      return "number";
    case "boolean":
    case "booleanLiteral":
      return "boolean";
    case "bigint":
      return "bigint";
    case "object":
    case "array":
    case "tuple":
    case "date":
    case "map":
    case "set":
      return "object";
    default:
      return null;
  }
}
