[package]
name = "site"

[package.scripts]
dev = "vite"
build = "tsc && vite build"
preview = "vite preview"

[package.dependencies]
"@fontsource/ibm-plex-mono" = "^5.2.7"
"@fontsource/schibsted-grotesk" = "^5.2.8"

[package.devDependencies]
"@solidjs/meta" = "^0.29.4"
"@solidjs/router" = "^0.15.0"
"@solidjs/start" = "2.0.0-alpha.2"
h3 = "2.0.1-rc.4"
nitro = "3.0.260311-beta"
vite = "^7.0.0"
solid-js = "^1.9.5"
solid-styled = "^0.12.1"
unplugin-solid-styled = "^0.12.1"

[tsconfig.compilerOptions]
target = "ESNext"
module = "ESNext"
moduleResolution = "bundler"
allowSyntheticDefaultImports = true
esModuleInterop = true
jsx = "preserve"
jsxImportSource = "solid-js"
allowJs = true
strict = true
noEmit = true
types = ["vite/client"]
isolatedModules = true
paths = { "~/*" = ["./src/*"] }

[tsconfig]
include = ["src"]
